on:
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/reusable.yml
  call2:
    uses: ./.github/workflows/reusable.yml
  call-matrix:
    strategy:
      matrix:
        num: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    uses: ./.github/workflows/reusable.yml
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "done"
